controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

translation_redirection:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        # this value can be an absolute path or an absolute URL
        route: 'maintenance_page'
#        # optionally you can define some arguments passed to the route
#        page: 'index'
#        version: 'current'
        # redirections are temporary by default (code 302) but you can make them permanent (code 301)
        permanent: true
        # add this to keep the original query string parameters when redirecting
        keepQueryParams: true
        # add this to keep the HTTP method when redirecting. The redirect status changes
        # * for temporary redirects, it uses the 307 status code instead of 302
        # * for permanent redirects, it uses the 308 status code instead of 301
        keepRequestMethod: true
        # add this to remove the original route attributes when redirecting
        ignoreAttributes: true